In [ ]:
# parse certain elements from patient resource of sample fhir from synthea
# easier way to parse: gcp healthcare api

from fhir.resources.bundle import Bundle
from fhir.resources.patient import Patient
from pathlib import Path
import json

def parse_patient(e,file):
    p = Patient.model_construct(**e['resource'])
    return (
        p.name[0]['given'][0],
        p.name[0]['family'],
        p.address[0]['city'],
        p.address[0]['state'],
        Path(file).name
    )

patient_data=[]

files = list(Path(r"C:\Users\hvu7470\Downloads\synthea_sample_data_fhir_latest").glob('*.json'))
file_count=0
for file in files[:]:
    file = Path(file)
    file_count += 1
    with open(file,"r", encoding='utf-8') as f:
        try:
            d = json.load(f)
        except Exception as e:
            print(f'couldnt parse {file.name}')
            
    bundle = Bundle.model_construct(**d)
    patients = [parse_patient(e,file) for e in bundle.entry if e['resource']['resourceType']=='Patient']
    if len(patients)<1: 
        print(f'no patients found for {file.name}')
    else:
        patient_data += patients

print(f'\n{file_count} out of {len(files)} files examined')


df=pd.DataFrame(patient_data,columns=['last','first','city','st','src'])
df.head(5)
df.tail(5)

no patients found for hospitalInformation1730906375349.json
no patients found for practitionerInformation1730906375349.json

108 out of 108 files examined

,last,first,city,st,src
0,Ada662,Balistreri607,Somerville,MA,Ada662_Sari509_Balistreri607_dbc4a3f7-9c69-443...
1,Adrianne466,Glover433,North Westport,MA,Adrianne466_Jonnie215_Glover433_99d3b9b2-46c1-...
2,Aleen595,Rogahn59,Worcester,MA,Aleen595_Alanna27_Rogahn59_5358446e-e631-c640-...
3,Aleisha941,Treutel973,Springfield,MA,Aleisha941_Treutel973_2d799deb-df07-0c4a-8692-...
4,Alena861,Gusikowski974,West Tisbury,MA,Alena861_Danna372_Gusikowski974_bd2a8021-2868-...

,last,first,city,st,src
101,Wade235,Emmerich580,Middleton,MA,Wade235_Emmerich580_13cc1678-474c-7932-a719-c6...
102,Willian804,Keeling57,Braintree,MA,Willian804_Keeling57_c1acd7ba-dacf-36d2-6010-d...
103,Yolanda648,Baca589,Reading,MA,Yolanda648_Baca589_355f70c7-b1f4-b1db-8843-56b...
104,Yun266,Ernser583,Fairhaven,MA,Yun266_Ernser583_37713015-cfb5-bf1a-70eb-97010...
105,Zenia843,Weimann465,West Tisbury,MA,Zenia843_Genesis248_Weimann465_655baba7-47ed-2...